//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.26323.1
// 
namespace ClientApp.ServiceRef {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryRow", Namespace="http://schemas.datacontract.org/2004/07/CodeFirst.Entities")]
    public partial class HistoryRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double CpsField;
        
        private double DeField;
        
        private double DerField;
        
        private System.Guid HistoryRowIdField;
        
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cps {
            get {
                return this.CpsField;
            }
            set {
                if ((this.CpsField.Equals(value) != true)) {
                    this.CpsField = value;
                    this.RaisePropertyChanged("Cps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double De {
            get {
                return this.DeField;
            }
            set {
                if ((this.DeField.Equals(value) != true)) {
                    this.DeField = value;
                    this.RaisePropertyChanged("De");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Der {
            get {
                return this.DerField;
            }
            set {
                if ((this.DerField.Equals(value) != true)) {
                    this.DerField = value;
                    this.RaisePropertyChanged("Der");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid HistoryRowId {
            get {
                return this.HistoryRowIdField;
            }
            set {
                if ((this.HistoryRowIdField.Equals(value) != true)) {
                    this.HistoryRowIdField = value;
                    this.RaisePropertyChanged("HistoryRowId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timetable", Namespace="http://schemas.datacontract.org/2004/07/ServiceForUWP")]
    public partial class Timetable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short busnumberField;
        
        private string busstationField;
        
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short busnumber {
            get {
                return this.busnumberField;
            }
            set {
                if ((this.busnumberField.Equals(value) != true)) {
                    this.busnumberField = value;
                    this.RaisePropertyChanged("busnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string busstation {
            get {
                return this.busstationField;
            }
            set {
                if ((object.ReferenceEquals(this.busstationField, value) != true)) {
                    this.busstationField = value;
                    this.RaisePropertyChanged("busstation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IDbServiceForUwp")]
    public interface IDbServiceForUwp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbServiceForUwp/GetHistoryRowsJson", ReplyAction="http://tempuri.org/IDbServiceForUwp/GetHistoryRowsJsonResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ClientApp.ServiceRef.HistoryRow>> GetHistoryRowsJsonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbServiceForUwp/AddHistoryRow", ReplyAction="http://tempuri.org/IDbServiceForUwp/AddHistoryRowResponse")]
        System.Threading.Tasks.Task AddHistoryRowAsync(ClientApp.ServiceRef.Timetable newRow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbServiceForUwp/AddHistory", ReplyAction="http://tempuri.org/IDbServiceForUwp/AddHistoryResponse")]
        System.Threading.Tasks.Task AddHistoryAsync(System.Collections.ObjectModel.ObservableCollection<ClientApp.ServiceRef.HistoryRow> newHistory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbServiceForUwp/DeleteHistoryRow", ReplyAction="http://tempuri.org/IDbServiceForUwp/DeleteHistoryRowResponse")]
        System.Threading.Tasks.Task DeleteHistoryRowAsync(ClientApp.ServiceRef.HistoryRow row);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbServiceForUwp/ClearHistory", ReplyAction="http://tempuri.org/IDbServiceForUwp/ClearHistoryResponse")]
        System.Threading.Tasks.Task ClearHistoryAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDbServiceForUwpChannel : ClientApp.ServiceRef.IDbServiceForUwp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DbServiceForUwpClient : System.ServiceModel.ClientBase<ClientApp.ServiceRef.IDbServiceForUwp>, ClientApp.ServiceRef.IDbServiceForUwp {
        
        public DbServiceForUwpClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ClientApp.ServiceRef.HistoryRow>> GetHistoryRowsJsonAsync() {
            return base.Channel.GetHistoryRowsJsonAsync();
        }
        
        public System.Threading.Tasks.Task AddHistoryRowAsync(ClientApp.ServiceRef.Timetable newRow) {
            return base.Channel.AddHistoryRowAsync(newRow);
        }
        
        public System.Threading.Tasks.Task AddHistoryAsync(System.Collections.ObjectModel.ObservableCollection<ClientApp.ServiceRef.HistoryRow> newHistory) {
            return base.Channel.AddHistoryAsync(newHistory);
        }
        
        public System.Threading.Tasks.Task DeleteHistoryRowAsync(ClientApp.ServiceRef.HistoryRow row) {
            return base.Channel.DeleteHistoryRowAsync(row);
        }
        
        public System.Threading.Tasks.Task ClearHistoryAsync() {
            return base.Channel.ClearHistoryAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
